export const LOAD_ANTS_REQUEST = 'LOAD_ANTS_REQUEST';
export const LOAD_ANTS_SUCCESS = 'LOAD_ANTS_SUCCESS';
export const GENERATE_WIN_LIKELIHOOD_START = 'GENERATE_WIN_LIKELIHOOD_START';
export const GENERATE_WIN_LIKELIHOOD_COMPLETE =
  'GENERATE_WIN_LIKELIHOOD_COMPLETE';
